version: "2"
services:
  easyappointments-data:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: easyappointments
      MYSQL_ROOT_PASSWORD: hellodocker

  easyappointments:
    image: jamrizzi/easyappointments:latest
    environment:
      DB_NAME: easyappointments
      DB_PASSWORD: hellodocker
      BASE_URL: http://localhost:8888
    ports:
      - 8888:8888
    links:
      - easyappointments-data:db

  ids:
    image: linton/docker-snort
    command: bash -c "snort -dev -c /etc/snort/etc/snort.conf"

  
    
    
