version: "3"
services:
  easyappointments-data:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: easyappointments
      MYSQL_ROOT_PASSWORD: hellodocker

  easyappointments:
    image: jamrizzi/easyappointments:latest
    environment:
      DB_NAME: easyappointments
      DB_PASSWORD: hellodocker
      BASE_URL: http://localhost:8888
    expose:
      - "8888"
    links:
      - easyappointments-data:db

  bot: 
    image: tutum/curl
    volumes: 
      - ./DDoSBotnet/DDoSBot/curlAttack.sh:/usr/bin/curlAttack.sh
    command: bash -c "./usr/bin/curlAttack.sh"

volumes:
  snortconf:
  localrules:
  curlattack: