//
// **** AUTOMATICALLY GENERATED BY mk-node-decls.pl -- DO NOT EDIT ****
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace gr8 {
class identity_node; 
class if_node; 
class func_define_node; 
class read_node; 
class print_node; 
class block_node; 
class objects_node; 
class func_declare_node; 
class stop_node; 
class var_init_node; 
class return_node; 
class null_node; 
class sweeping_node; 
class evaluation_node; 
class index_node; 
class again_node; 
class if_else_node; 
class pos_indication_node; 
class func_call_node; 

} // namespace gr8

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_gr8_NODE_ALLNODES_H__
#define __AUTOMATIC_gr8_NODE_ALLNODES_H__

#include "ast/identity_node.h"
#include "ast/if_node.h"
#include "ast/func_define_node.h"
#include "ast/read_node.h"
#include "ast/print_node.h"
#include "ast/block_node.h"
#include "ast/objects_node.h"
#include "ast/func_declare_node.h"
#include "ast/stop_node.h"
#include "ast/var_init_node.h"
#include "ast/return_node.h"
#include "ast/null_node.h"
#include "ast/sweeping_node.h"
#include "ast/evaluation_node.h"
#include "ast/index_node.h"
#include "ast/again_node.h"
#include "ast/if_else_node.h"
#include "ast/pos_indication_node.h"
#include "ast/func_call_node.h"


#endif /* !defined(__AUTOMATIC_gr8_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */
